### ISSUE TITLE
curl options error

### ISSUE THREAD

**Issue by iLoooordFx** [dcoles/pycurl-requests#2]
TypeError: request() got an unexpected keyword argument 'curl'

**Comment by dcoles** [comment]
Thank you for your bug report.

The [cURL options example](https://github.com/dcoles/pycurl-requests/blob/v0.1.0/README.md#curl-options) in the [latest release (0.1.0)](https://pypi.org/project/pycurl-requests/0.1.0/) no longer works as of d1c8e02c6e1deacf3f32fd1216e404ac0253f1c4 ("Add basic Session support").

I'll have to think about whether this should be exposed via the [main interface](https://requests.readthedocs.io/en/master/api/#main-interface), or if it should be restricted to the [request Session object](https://requests.readthedocs.io/en/master/api/#request-sessions).

In the mean time, here's how to set cURL options on a request:

```python
import pycurl
import pycurl_requests as requests

with requests.Session() as session:
    session.curl.setopt(pycurl.NOBODY, 1)
    response = session.get('http://example.com')
````

**Comment by dcoles** [comment]
Updated the README with the [new method of setting cURL options](https://github.com/dcoles/pycurl-requests/blob/v0.1.1/README.md#curl-options).
