### ISSUE TITLE
Remove pytest from the reuirements

### ISSUE THREAD

**Issue by mlech-reef** [dcoles/pycurl-requests#4]
Please remove `pytest` from the requirements

**Comment by dcoles** [comment]
Thanks for the bug report. I've removed from `install_requires` and `requirements.txt`. 

I've tagged this as [`pycurl-requests-0.1.2`](https://pypi.org/project/pycurl-requests/0.1.2/).

**Comment by mlech-reef** [comment]
Thank you for your very fast response
